"""add operation to appointment sync logs

Revision ID: 1c46c799b02d
Revises: b50a58a24693
Create Date: 2026-03-18 00:17:04.667484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c46c799b02d'
down_revision: Union[str, Sequence[str], None] = 'b50a58a24693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_sync_logs', sa.Column('operation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_sync_logs', 'operation')
    # ### end Alembic commands ###
