"""added a new column clinic_timezone

Revision ID: 4b78552f4ce6
Revises: 549e62622b06
Create Date: 2025-11-12 00:22:33.572807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b78552f4ce6'
down_revision: Union[str, Sequence[str], None] = '549e62622b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('calendar_id', sa.String(), nullable=False))
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('patients', 'Gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('registered_clinics', sa.Column('clinic_timezone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_clinics', 'clinic_timezone')
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'Gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'end_time',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('appointments', 'calendar_id')
    # ### end Alembic commands ###
