"""create initial tables

Revision ID: 549e62622b06
Revises: 
Create Date: 2025-11-01 00:00:27.682259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549e62622b06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('Dsos',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Dsos_id'), 'Dsos', ['id'], unique=True)
    op.create_table('registered_clinics',
    sa.Column('crm_type', sa.String(), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=False),
    sa.Column('clinic_number', sa.Integer(), nullable=False),
    sa.Column('od_developer_key', sa.String(), nullable=False),
    sa.Column('od_customer_key', sa.String(), nullable=False),
    sa.Column('crm_api_key', sa.String(), nullable=False),
    sa.Column('operatory_calendar_map', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('dso_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_clinics_id'), 'registered_clinics', ['id'], unique=True)
    op.create_table('patients',
    sa.Column('FName', sa.String(), nullable=True),
    sa.Column('LName', sa.String(), nullable=True),
    sa.Column('Gender', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('pat_num', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'contact_id', name='uq_clinic_contactid'),
    sa.UniqueConstraint('clinic_id', 'pat_num', name='uq_clinic_patnum')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=True)
    op.create_table('appointments',
    sa.Column('AptNum', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('pat_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pat_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'AptNum', name='uq_clinic_AptNum'),
    sa.UniqueConstraint('clinic_id', 'event_id', name='uq_clinic_eventid')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_registered_clinics_id'), table_name='registered_clinics')
    op.drop_table('registered_clinics')
    op.drop_index(op.f('ix_Dsos_id'), table_name='Dsos')
    op.drop_table('Dsos')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
