"""add user active status columns

Revision ID: 5fb0f36cad8e
Revises: b4f77625b472
Create Date: 2026-04-13 19:05:32.705938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb0f36cad8e'
down_revision: Union[str, Sequence[str], None] = 'b4f77625b472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_role_assignments_user_scope_clinic_active', 'role_assignments', ['user_id', 'scope_type', 'clinic_id', 'is_active'], unique=False)
    op.create_index('ix_role_assignments_user_scope_dso_active', 'role_assignments', ['user_id', 'scope_type', 'dso_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_assignments_user_scope_dso_active', table_name='role_assignments')
    op.drop_index('ix_role_assignments_user_scope_clinic_active', table_name='role_assignments')
    # ### end Alembic commands ###
