"""add toroforge wallet and funding schema

Revision ID: 7291c76b408b
Revises: efd6c4b95fb6
Create Date: 2026-05-12 15:47:03.515778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7291c76b408b'
down_revision: Union[str, Sequence[str], None] = 'efd6c4b95fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('external_wallet_username', sa.String(), nullable=True))
    op.add_column('wallets', sa.Column('external_wallet_password_encrypted', sa.String(), nullable=True))
    op.create_index(op.f('ix_wallets_external_wallet_username'), 'wallets', ['external_wallet_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_external_wallet_username'), table_name='wallets')
    op.drop_column('wallets', 'external_wallet_password_encrypted')
    op.drop_column('wallets', 'external_wallet_username')
    # ### end Alembic commands ###
