"""add webhook_secret to registered clinics

Revision ID: 749b6eea860b
Revises: b3a0a57f4c1d
Create Date: 2026-03-10 12:29:44.680602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749b6eea860b'
down_revision: Union[str, Sequence[str], None] = 'b3a0a57f4c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_clinics', sa.Column('webhook_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_clinics', 'webhook_secret')
    # ### end Alembic commands ###
