"""add clinic disable fields and sync log search

Revision ID: b29a40fdd53a
Revises: 6663de09cbc9
Create Date: 2026-04-11 15:43:10.375071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29a40fdd53a'
down_revision: Union[str, Sequence[str], None] = '6663de09cbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_sync_logs', sa.Column('patient_name_search', sa.String(), nullable=True))
    op.create_index(op.f('ix_appointment_sync_logs_patient_name_search'), 'appointment_sync_logs', ['patient_name_search'], unique=False)
    op.add_column('registered_clinics', sa.Column('is_disabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('registered_clinics', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('registered_clinics', sa.Column('disabled_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_registered_clinics_is_disabled'), 'registered_clinics', ['is_disabled'], unique=False)
    op.create_foreign_key(None, 'registered_clinics', 'users', ['disabled_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registered_clinics', type_='foreignkey')
    op.drop_index(op.f('ix_registered_clinics_is_disabled'), table_name='registered_clinics')
    op.drop_column('registered_clinics', 'disabled_by')
    op.drop_column('registered_clinics', 'disabled_at')
    op.drop_column('registered_clinics', 'is_disabled')
    op.drop_index(op.f('ix_appointment_sync_logs_patient_name_search'), table_name='appointment_sync_logs')
    op.drop_column('appointment_sync_logs', 'patient_name_search')
    # ### end Alembic commands ###
