"""add user active status columns

Revision ID: b4f77625b472
Revises: b29a40fdd53a
Create Date: 2026-04-13 18:53:06.216897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f77625b472'
down_revision: Union[str, Sequence[str], None] = 'b29a40fdd53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('registered_clinics_owner_id_fkey'), 'registered_clinics', type_='foreignkey')
    op.create_foreign_key(None, 'registered_clinics', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'registered_clinics', type_='foreignkey')
    op.create_foreign_key(op.f('registered_clinics_owner_id_fkey'), 'registered_clinics', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
