"""harden phi storage

Revision ID: b50a58a24693
Revises: afe59147b6e7
Create Date: 2026-03-17 11:43:51.950789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b50a58a24693'
down_revision: Union[str, Sequence[str], None] = 'afe59147b6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_sync_logs', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('inbound_events', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('patients', sa.Column('contact_id_hash', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_clinic_contactid'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_contact_id_hash'), 'patients', ['contact_id_hash'], unique=False)
    op.create_unique_constraint('uq_clinic_contactid_hash', 'patients', ['clinic_id', 'contact_id_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_clinic_contactid_hash', 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_contact_id_hash'), table_name='patients')
    op.create_unique_constraint(op.f('uq_clinic_contactid'), 'patients', ['clinic_id', 'contact_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'contact_id_hash')
    op.alter_column('inbound_events', 'payload',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('appointment_sync_logs', 'payload',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
