"""add Kyc field

Revision ID: d64762c7874a
Revises: 920ea50e49c4
Create Date: 2026-06-01 10:50:41.607179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64762c7874a'
down_revision: Union[str, Sequence[str], None] = '920ea50e49c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('kyc_verified', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_wallets_kyc_verified'), 'wallets', ['kyc_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_kyc_verified'), table_name='wallets')
    op.drop_column('wallets', 'kyc_verified')
    # ### end Alembic commands ###
